### ISSUE TITLE
Cannot resolve node-fetch

### ISSUE THREAD

**Issue by jonpepler** [formidable-webview/ersatz#4]
When installing the ersatz package with a node version >10, I get the following error which seems like unexpected behaviour:

```
error fetch-blob@1.0.7: The engine "node" is incompatible with this module. Expected version "^10.17.0". Got "16.0.0"
error Found incompatible module.
```

If I choose to ignore the issue and pass `--ignore-engines` (not ideal I realise, but it's not obvious to me that this should cause serious issues), I then get the following error after importing the package:

```
 BUNDLE  ./index.js 

error: Error: While trying to resolve module `node-fetch` from file `[path/to/my/code]/node_modules/@formidable-webview/ersatz/lib/commonjs/SourceLoader.js`, the package `[path/to/my/code]/node_modules/@formidable-webview/ersatz/node_modules/node-fetch/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`[path/to/my/code]/node_modules/@formidable-webview/ersatz/node_modules/node-fetch/dist/index.cjs`. Indeed, none of these files exist:

  * [path/to/my/code]/node_modules/@formidable-webview/ersatz/node_modules/node-fetch/dist/index.cjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * [path/to/my/code]/node_modules/@formidable-webview/ersatz/node_modules/node-fetch/dist/index.cjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency ([path/to/my/code]/node_modules/metro/src/node-haste/DependencyGraph.js:436:17)
    at Object.resolve ([path/to/my/code]/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve ([path/to/my/code]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at [path/to/my/code]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies ([path/to/my/code]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at [path/to/my/code]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep ([path/to/my/code]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
    at _next ([path/to/my/code]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:9)

```

I'm keen to use this package in my project but I have been going in circles staring at these errors for a while. I'd really appreciate some guidance, information on why this might be expected, or anything I can do to help. Thanks!

**Comment by jsamr** [comment]
@jonpepler It looks like you are trying to use Ersatz with the metro bundler? The "error message" you are showing comes from the metro bundler). This package is meant to be used with jest only, so you should not import Ersatz outside of tests! Could you share a repository reproduction?

**Comment by jonpepler** [comment]
Hi @jsamr, thanks for the quick response and your information, that makes sense! I've not been able to successfully run Ersatz in our project I think due to our testing configuration, but I have been able to get it running just fine on a fresh project. Thanks for your patience!
